version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: ./.docker/python/Dockerfile
    container_name: django.python
    image: django.python
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - django
    ports:
      - "8000:8000"
    command: uvicorn app_name.asgi:application --host 0.0.0.0 --port 8000 --reload
    restart: always

  mysql:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    container_name: django.mysql
    image: django.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django
      MYSQL_DATABASE: django
      MYSQL_PASSWORD: django
    volumes:
      - ./.docker/mysql/database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - django
    depends_on:
      - python
    ports:
      - "3306:3306"

networks:
  django:
    driver: bridge