version: '3.8'

services:

  mysql:
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    container_name: container_name
    image: image_name
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/mysql/database:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"