name: develop ci

on:
  pull_request:
    branches: ["develop"]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: create virtual environment
        run: python -m venv .venv

      - name: install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: install dev dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements-dev.txt

      - name: check code style with flake8
        run: |
          set -e
          source .venv/bin/activate
          flake8

      - name: using black to format code.
        run: |
          set -e
          source .venv/bin/activate
          black --check .